[project]
name = "aiida-reoptimize"
version = "0.8.0"
description = "Algorithms for external optimization of crystal structures"
authors = [{name = "Anton Domnin",email = "a.v.daomnin@gmail.com"},]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: AiiDA",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Information Analysis"
]
keywords = ["aiida", "plugin", "fleur", "crystal"]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10,<3.16"
dependencies = [
    "pymoo>=0.6.1.6,<0.7",
    "aiida-core>=2.5,<3",
    "mpds_client",
    "ase",
    "spglib>=2.6.0",
    "ase-fleur @ git+https://github.com/JuDFTteam/ase-fleur",
    "aiida-fleur>=2.0.0",
    "aiida-crystal-dft @ git+https://github.com/tilde-lab/aiida-crystal-dft"
]

[project.urls]
Source = "https://github.com/mpds-io/aiida-reoptimize"

[project.entry-points."aiida.workflows"]
"aiida_reoptimize.AdamFleurRelaxOptimizer" = "aiida_reoptimize.workflows.Optimization.FleurRelax:AdamFleurRelaxOptimizer"
"aiida_reoptimize.RMSpropFleurRelaxOptimizer" = "aiida_reoptimize.workflows.Optimization.FleurRelax:RMSpropFleurRelaxOptimizer"
"aiida_reoptimize.BFGSFleurRelaxOptimizer" = "aiida_reoptimize.workflows.Optimization.FleurRelax:BFGSFleurRelaxOptimizer"
"aiida_reoptimize.PyMOOFleurRelaxOptimizer" = "aiida_reoptimize.workflows.Optimization.FleurRelax:PyMOOFleurRelaxOptimizer"
"aiida_reoptimize.G3PCXFleurRelaxOptimizer" = "aiida_reoptimize.workflows.Optimization.FleurRelax:G3PCXFleurRelaxOptimizer"
"aiida_reoptimize.NRBOFleurRelaxOptimizer" = "aiida_reoptimize.workflows.Optimization.FleurRelax:NRBOFleurRelaxOptimizer"
"aiida_reoptimize.CDGFleurRelaxOptimizer" = "aiida_reoptimize.workflows.Optimization.FleurRelax:CDGFleurRelaxOptimizer"
"aiida_reoptimize.AdamFleurSCFOptimizer" = "aiida_reoptimize.workflows.Optimization.FleurSCF:AdamFleurSCFOptimizer"
"aiida_reoptimize.RMSpropFleurSCFOptimizer" = "aiida_reoptimize.workflows.Optimization.FleurSCF:RMSpropFleurSCFOptimizer"
"aiida_reoptimize.BFGSFleurSCFOptimizer" = "aiida_reoptimize.workflows.Optimization.FleurSCF:BFGSFleurSCFOptimizer"
"aiida_reoptimize.PyMOOFleurSCFOptimizer" = "aiida_reoptimize.workflows.Optimization.FleurSCF:PyMOOFleurSCFOptimizer"
"aiida_reoptimize.G3PCXFleurSCFOptimizer" = "aiida_reoptimize.workflows.Optimization.FleurSCF:G3PCXFleurSCFOptimizer"
"aiida_reoptimize.NRBOFleurSCFOptimizer" = "aiida_reoptimize.workflows.Optimization.FleurSCF:NRBOFleurSCFOptimizer"
"aiida_reoptimize.CDGFleurSCFOptimizer" = "aiida_reoptimize.workflows.Optimization.FleurSCF:CDGFleurSCFOptimizer"
"aiida_reoptimize.AdamCrystalOptimizer" = "aiida_reoptimize.workflows.Optimization.Crystal:AdamCrystalOptimizer"
"aiida_reoptimize.CDGCrystalOptimizer" = "aiida_reoptimize.workflows.Optimization.Crystal:CDGCrystalOptimizer"
"aiida_reoptimize.RMSpropCrystalOptimizer" = "aiida_reoptimize.workflows.Optimization.Crystal:RMSpropCrystalOptimizer"
"aiida_reoptimize.BFGSCrystalOptimizer" = "aiida_reoptimize.workflows.Optimization.Crystal:BFGSCrystalOptimizer"
"aiida_reoptimize.PyMOOCrystalOptimizer" = "aiida_reoptimize.workflows.Optimization.Crystal:PyMOOCrystalOptimizer"
"aiida_reoptimize.G3PCXCrystalOptimizer" = "aiida_reoptimize.workflows.Optimization.Crystal:G3PCXCrystalOptimizer"
"aiida_reoptimize.NRBOCrystalOptimizer" = "aiida_reoptimize.workflows.Optimization.Crystal:NRBOCrystalOptimizer"
"aiida_reoptimize.FleurSCFLatticeProblem" = "aiida_reoptimize.workflows.Evaluation.fleur_evaluators:FleurSCFLatticeProblem"
"aiida_reoptimize.FleurRelaxLatticeProblem" = "aiida_reoptimize.workflows.Evaluation.fleur_evaluators:FleurRelaxLatticeProblem"
"aiida_reoptimize.CrystalLatticeProblem" = "aiida_reoptimize.workflows.Evaluation.crystal_evaluation:CrystalLatticeProblem"

[dependency-groups]
dev = [
    "ruff>=0.6.9,<0.7",
]

[tool.uv]
default-groups = ["dev"]
