[project]
name = "aiida-reoptimize"
version = "0.4.0"
description = "Calculators for external optimization of crystal structures."
authors = [
    {name = "Anton Domnin",email = "a.v.daomnin@gmail.com"},
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11,<4"
dependencies = [
    "pymoo==0.6.1.3",
    "aiida-core (>=2.6.4,<3.0.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.9"
